spring:
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          starttls:
            enable: 'true'
          ssl:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: ${CLIENT_MAIL_USERNAME}
    password: ${CLIENT_MAIL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: ${DB_SQL_PASSWORD}
    username: ${DB_SQL_USERNAME}
    url: ${DB_SQL_URL}
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write_dates_as_timestamps: false
  servlet:
    multipart:
      max-file-size: '10MB'

application:
  reset-password-url: ${RESET_PASSWORD_WEB_URL}
  smtp-sender: test@example.com
auth:
  reset-password-token-expiration-miliseg: '900000'
  public-sign-up-url-enable: 'true'

aws:
  s3:
    access-key: ${AWS_CREDENTIALS_ACCESSKEY}
    secret-key: ${AWS_CREDENTIALS_SECRET_KEY}
    bucket:
      name: 'img-profile'

encrypted:
  secretJwt: ${JWT_SECRET}

jwt:
  expiration: '86400000'
